name: signature-verification

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9.18
  - scikit-learn=1.3.0
  - numpy=1.24.3
  - pandas=2.0.3
  - opencv=4.8.0
  - pillow=10.0.0
  - imageio=2.31.1
  - scipy=1.11.1
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - tqdm=4.65.0
  - joblib=1.3.2
  - jupyter=1.0.0
  - ipykernel=6.25.0
  - pytest=7.4.0
  - pip=23.2.1
  - fastapi      # added
  - uvicorn      # added
  - pip:
    - tensorflow==2.13.0
    - keras==2.13.1
    - efficientnet-pytorch==0.7.1
    - albumentations==1.3.1
    - imgaug==0.4.0
    - python-dotenv==1.0.0
    - loguru==0.7.2
    - PyYAML==6.0.1
