name: signature-verification
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.9.18
  
  # Core ML libraries (use pip for TF + Keras)
  - scikit-learn=1.3.0
  - numpy=1.24.3
  - pandas=2.0.3
  
  # Image processing
  - opencv=4.8.0
  - pillow=10.0.0
  - imageio=2.31.1
  
  # Scientific computing
  - scipy=1.11.1
  - matplotlib=3.7.2
  - seaborn=0.12.2
  
  # Utilities
  - tqdm=4.65.0
  - joblib=1.3.2
  # removed pickle5 (built into Python >=3.8)
  
  # Development tools
  - jupyter=1.0.0
  - ipykernel=6.25.0
  - pytest=7.4.0
  
  # Pip dependencies
  - pip=23.2.1
  - pip:
    - tensorflow==2.13.0
    - keras==2.13.1
    - efficientnet-pytorch==0.7.1
    - albumentations==1.3.1
    - imgaug==0.4.0
    - python-dotenv==1.0.0
    - loguru==0.7.2
    - PyYAML==6.0.1
