name: signature-verification
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  
  # Core Scientific Computing
  - numpy<2.0
  - pandas
  - scipy
  - matplotlib
  - seaborn
  
  # Machine Learning Core
  - scikit-learn
  - tensorflow
  - keras
  
  # Computer Vision
  - opencv
  - pillow
  - imageio
  
  # Statistical Analysis
  - statsmodels
  
  # Visualization & Plotting
  - plotly
  - bokeh
  
  # Development Tools
  - jupyter
  - notebook
  - tqdm
  
  # Performance Monitoring
  - psutil
  
  - pip:
      # Advanced Plotting
      - plotly-express
      - kaleido  # For plotly image export
      
      # Research Metrics
      - scikit-plot
      - yellowbrick
      
      - uvicorn
      - fastapi
      # Model Analysis
      - tensorboard
      
      # Image Processing
      - scikit-image
      - imutils
      
      # Data Export
      - openpyxl
      - xlsxwriter
      
      # Research Documentation
      - tabulate
      - fpdf2